language: ruby
sudo: required
rvm:
  - 2.3.1
addons:
  postgresql: "9.5"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - ENV['RACK_ENV']=test bundle exec rake db:migrate
  - bundle exec rspec spec