language: ruby
sudo: required
rvm:
  - 2.3.1
addons:
  postgresql: "9.5"
  code_climate:
    repo_token: 189045fd419c68bc74f87681f2298dc92b051266648101ccda63210e57db43cd
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - ENV['RACK_ENV']=test bundle exec rake db:migrate
  - bundle exec rspec spec
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  api_key: $HEROKU_STAGING_API_KEY
  app: weathersms
